# Homebrew formula for imail.
#
# This file is the source-of-truth for the formula. To publish it on a
# personal tap so `brew install jessecu2024/tap/imail` works:
#
#   1. Create a public GitHub repository named `homebrew-tap` under
#      jessecu2024 (any name prefixed with `homebrew-` works).
#   2. `cp packaging/homebrew/imail.rb /path/to/homebrew-tap/Formula/imail.rb`
#   3. Generate the resource blocks for every Python dependency (see below).
#   4. Commit and push the tap.
#   5. Users: `brew tap jessecu2024/tap && brew install imail`
#
# Generating resources (re-run on every imail-cli version bump):
#
#   pipx install homebrew-pypi-poet
#   pip install imail-cli==<version>
#   poet imail-cli > resources.rb
#   # Then paste the contents of resources.rb in place of the marker below.
#
# The Language::Python::Virtualenv helper handles isolating imail's deps
# in a private venv inside the Cellar — they don't pollute Homebrew's
# global site-packages.

class Imail < Formula
  include Language::Python::Virtualenv

  desc "Inbox triage as a local app: 3 LLM-drafted replies per email"
  homepage "https://github.com/jessecu2024/imail"
  url "https://files.pythonhosted.org/packages/source/i/imail-cli/imail_cli-1.3.0.tar.gz"
  # Run `shasum -a 256 imail_cli-1.3.0.tar.gz` after downloading from PyPI
  # to fill in. Update on every release.
  sha256 "<<<PLACEHOLDER — run shasum -a 256 on the sdist>>>"
  license "MIT"

  depends_on "python@3.12"

  # ============================================================
  # PYTHON DEPENDENCY RESOURCES — generated by `poet imail-cli`.
  # Paste the output here. Each looks like:
  #
  #   resource "fastapi" do
  #     url "https://files.pythonhosted.org/.../fastapi-0.x.tar.gz"
  #     sha256 "..."
  #   end
  #
  # Without these, `brew install` would fall back to pip's resolver and
  # the build wouldn't be reproducible.
  # ============================================================

  def install
    virtualenv_install_with_resources
  end

  test do
    output = shell_output("#{bin}/imail --version")
    assert_match "imail", output
  end
end
